name: CI

# This `on:` configuration avoids double-triggered jobs (one for `push`, one for `pull_request`).
# Pull requests will still get jobs on every commit.
# However you won't get jobs on branch pushes that lack an associated pull requests.
# On the other hand, CircleCI jobs will still be triggered, which give a useful form of feedback.
# Lastly, remember that we have a Makefile for local development - you are encouraged to use it before pushing commits.
on:
  push:
    branches:
      # - master
  pull_request:

permissions:
  contents: read #  to fetch code (actions/checkout)

jobs:
  integration:
    # Run integration tests for all OSs and EMACS_VERSIONs.
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        # os: [macos-13, ubuntu-latest, windows-latest]
        os: [ubuntu-latest]

        # java_version: ['11', '17']
        java_version: ['11']

    steps:

    - name: Install deps.clj on MS-Windows
      if: startsWith (matrix.os, 'windows')
      run: |
        iwr -Uri https://raw.githubusercontent.com/borkdude/deps.clj/master/install.ps1 -outfile install_clojure.ps1
        .\install_clojure.ps1
        get-command deps.exe | split-path -parent | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Check out the source code
      uses: actions/checkout@v2

    - name: Prepare java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        # shadow requires java 11
        java-version: ${{matrix.java_version}}

    - name: Install Clojure Tools
      # Use SHA until
      # https://github.com/DeLaGuardo/setup-clojure/issues/78 is
      # released
      uses: DeLaGuardo/setup-clojure@1376ded6747c79645e82c856f16375af5f5de307
      with:
        # bb: '1.0.165'
        cli: '1.10.3.1013'
        # lein: '2.9.10'

    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm install

    # - run: npm install shadow-cljs@2.20.13 -g
    # - run: npm install nbb@1.1.152 -g

    # - uses: actions/setup-python@v5
    #   with:
    #     python-version: '3.12'
    # - run: |
    #     pip install basilisp==0.1.0b2

    - name: compile
      run: |
        npm run compile

    - name: Test integration
      run: |
        npm run integration-test

